name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  issue-open-check:
    permissions:
      contents: read  # for visiky/dingtalk-release-notify to get latest release
      issues: write  # for actions-cool/issues-helper to update issues
      pull-requests: write  # for actions-cool/issues-helper to update PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@v2
        id: checkUser
        with:
          require: 'write'
          check-bot: true

      - name: check invalid
        if: (contains(github.event.issue.body, 'issue-helper') == false) && (steps.checkUser.outputs.require-result == 'false')
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'invalid'
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not conform to our issue requirements. Please fill the content in the template, thank you!

            你好 @${{ github.event.issue.user.login }}，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。请认真填写 ISSUE 模板内容。谢谢配合！

      - name: Add bug label
        if: contains(github.event.issue.body, '__BUG__') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'bug'

      - name: Add feature label
        if: contains(github.event.issue.body, '__FEATURE_REQUEST__') == true
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'feature'